### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by mcdent** [dieterdeyke/WAMPES#1]
Hey Dieter!
I used to use WAMPES back in the early 1990's! Before any of the NOS variants ran well on *NIX and before AX25
was part of the linux kernel. I am surprised but happy to stumble upon it on github.
I have a feeling I ran it on ISC unix or SYSV unix, I cant be sure which .
Anyway, thanks !
73 de Mike (g6phf)
UK

**Comment by dieterdeyke** [comment]
mcdent ***@***.***> writes:

> Hey Dieter!
> I used to use WAMPES back in the early 1990's! Before any of the NOS variants ran well on *NIX and
> before AX25
> was part of the linux kernel. I am surprised but happy to stumble upon it on github.
> I have a feeling I ran it on ISC unix or SYSV unix, I cant be sure which .
> Anyway, thanks !
> 73 de Mike (g6phf)
> UK

Thanks for those nice words, Mike. I did not want the code to get lost,
so I put it on GitHub, but I fear that it is there mostly to show the
history, not for much practical use. Anyway, it was really nice to hear
from you!

73,
-- 
Dieter Deyke
***@***.***
Get my Gnupg key:
gpg --keyserver keys.gnupg.net --recv-keys B116EA20
